services:
  mysql:
    image: mysql:8.0
    container_name: ecommerce_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: ECommerceDb_Dev
      MYSQL_USER: ecommerce_user
      MYSQL_PASSWORD: ecommerce_pass
    ports:
      - "3307:3306"
    volumes:
      - ecommerce_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p12345678"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: src/ECommerce.API/Dockerfile
    container_name: ecommerce_api
    restart: always
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: "8080"
      ConnectionStrings__DefaultConnection: "Server=mysql;Port=3306;Database=ECommerceDb_Dev;User=ecommerce_user;Password=ecommerce_pass;"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  ecommerce_mysql_data: