name: Backend CI

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'ECommerceBackend/**'
      - '.github/workflows/backend-ci.yml'

  pull_request:
    branches:
      - main
      - master
    paths:
      - 'ECommerceBackend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./ECommerceBackend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore packages
        run: dotnet restore src/ECommerce.API/ECommerce.API.csproj

      - name: Build API
        run: dotnet build src/ECommerce.API/ECommerce.API.csproj --configuration Release --no-restore