name: Backend CI

on:
  push:
    branches:
      - main
    paths:
      - 'ECommerceBackend/**'
      - '.github/workflows/backend-ci.yml'

  pull_request:
    branches:
      - main
    paths:
      - 'ECommerceBackend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./ECommerceBackend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore packages
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore